In [27]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [28]:
import numpy as np

In [29]:
# 1.1创建一个一维数组
d1 = np.array([1,2,3,4,5])
d1

array([1, 2, 3, 4, 5])

In [30]:
# 属性：size数据大小
d1.size

5

In [31]:
type(d1)

numpy.ndarray

In [32]:
# 属性：ndim数据维度
d1.ndim

1

In [33]:
# 1.2创建二维数组
d2 = np.arange(15)
d2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
# 增加行、列维度
d2 = d2.reshape(3,5)
d2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [35]:
# 打印一下相关属性
d2.size

15

In [36]:
d2.ndim

2

In [37]:
type(d1)

numpy.ndarray

In [38]:
# numpy官网地址：numpy.org / numpy.org.cn
np.array?