## 1.3.1 索引

* 单个元素索引：一维数组、负数索引
* 二维数组的索引

## 1.3.2 切片

* 切片
* 跨步
* 索引数组：针对多维数组的索引
* 索引结合切片

*更多参考：[NumPy中文网-索引部分](https://www.numpy.org.cn/user/basics/indexing.html#%E8%B5%8B%E5%80%BC%E4%B8%8E%E5%BC%95%E7%94%A8)*

In [26]:
import numpy as np

In [27]:
# 1.3.1 一维数组索引
array1 = np.array([1,2,3,4,5])
array1

array([1, 2, 3, 4, 5])

In [28]:
# 取第4个数值
array1[3]`

SyntaxError: invalid syntax (2959065993.py, line 2)

In [29]:
array1[-2]

4

In [30]:
# 二维数组
array2 = np.arange(14).reshape(2,7)
array2

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13]])

In [31]:
array2[0,3]

3

In [32]:
array2[0][3]

3

In [33]:
array2[1,-1]

13

In [34]:
array2[1,-2]

12

In [35]:
array2[-1,-1]

13

In [36]:
# 三维数组
array3 = np.arange(30).reshape(2,3,5)
array3

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [37]:
array3[0,1,2]

7

In [38]:
array3[0][1][2]

7

In [39]:
# 1.3.2 切片
array1

array([1, 2, 3, 4, 5])

In [40]:
array1[0:3] # a~b，a<=x<b

array([1, 2, 3])

In [41]:
array1[2:6]

array([3, 4, 5])

In [42]:
array1[2:]

array([3, 4, 5])

In [43]:
array1[:-1]

array([1, 2, 3, 4])

In [44]:
# 二维数组切片
array2

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13]])

In [45]:
array2[1:,:] # 行参数、列参数

array([[ 7,  8,  9, 10, 11, 12, 13]])

In [46]:
array2[:,3:4]

array([[ 3],
       [10]])

In [47]:
array2[1:,3:4]

array([[10]])

In [48]:
# 三维数组
array3

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [49]:
array3[0:1,2:,:]

array([[[10, 11, 12, 13, 14]]])

In [50]:
#array3[0:1,2:,:][2]

In [51]:
array3[0:1,2:,:][0,0,2] # 索引结合切片

12

In [52]:
# 索引多个数值
array1

array([1, 2, 3, 4, 5])

In [53]:
array1[np.array([0,2,4])]

array([1, 3, 5])

In [54]:
# 二维数组
array2

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13]])

In [55]:
array2[np.array([0,1]), np.array([1,2])]

array([1, 9])